package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"

	"github.com/example/auth0-gqlgen-demo/auth"
	"github.com/example/auth0-gqlgen-demo/graph/model"
)

// CreateAccountIfNotExists is the resolver for the createAccountIfNotExists field.
func (r *mutationResolver) CreateAccountIfNotExists(ctx context.Context) (*model.Account, error) {
	// Get authenticated user from context
	user, err := auth.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Use email from token, or use userID if email is empty (for M2M tokens)
	email := user.Email
	if email == "" {
		email = user.UserID + "@client.local"
	}

	// Create or retrieve account
	account, err := r.Store.CreateAccountIfNotExists(user.UserID, email)
	if err != nil {
		return nil, fmt.Errorf("failed to create account: %w", err)
	}

	return account, nil
}

// GetAccount is the resolver for the getAccount field.
func (r *queryResolver) GetAccount(ctx context.Context) (*model.Account, error) {
	// Get authenticated user from context
	user, err := auth.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Retrieve account
	account, err := r.Store.GetAccountByUserID(user.UserID)
	if err != nil {
		return nil, fmt.Errorf("account not found: %w", err)
	}

	return account, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
