// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	UserID    string `json:"userId"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}
